"""test

Revision ID: 0a05066dcb91
Revises: d4c79c6731d6
Create Date: 2023-06-07 08:23:57.214685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a05066dcb91'
down_revision = 'd4c79c6731d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
