"""newest

Revision ID: 1e1cb4269c7d
Revises: 294eca9fcf25
Create Date: 2023-06-08 14:17:12.301995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1cb4269c7d'
down_revision = '294eca9fcf25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
