"""test

Revision ID: 268e4099a55e
Revises: b61b427cd0a6
Create Date: 2023-06-05 21:29:13.544217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268e4099a55e'
down_revision = 'b61b427cd0a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
