"""test1

Revision ID: 27651d1744ab
Revises: fd028f033099
Create Date: 2023-06-05 22:51:37.833456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27651d1744ab'
down_revision = 'fd028f033099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
