"""refactor

Revision ID: 294eca9fcf25
Revises: 4ac47acd99ea
Create Date: 2023-06-07 09:51:42.313687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294eca9fcf25'
down_revision = '4ac47acd99ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
