"""trying it4

Revision ID: 34d5b67e6139
Revises: 9491838ef7f2
Create Date: 2023-06-05 13:14:19.621612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d5b67e6139'
down_revision = '9491838ef7f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
