"""test1

Revision ID: 3b0248101295
Revises: efaf8cdbcc5b
Create Date: 2023-06-05 23:00:29.607250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0248101295'
down_revision = 'efaf8cdbcc5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
