"""test

Revision ID: 44ef3d6523f1
Revises: 46c06bcf02ef
Create Date: 2023-06-06 21:14:45.980381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ef3d6523f1'
down_revision = '46c06bcf02ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
