"""test1

Revision ID: 46c06bcf02ef
Revises: 87e7f624b073
Create Date: 2023-06-05 23:57:04.323928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c06bcf02ef'
down_revision = '87e7f624b073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
