"""test1

Revision ID: 4b2628c7ff19
Revises: c3294c1f9256
Create Date: 2023-06-05 23:21:56.474742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2628c7ff19'
down_revision = 'c3294c1f9256'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
