"""test1

Revision ID: 51711970a58c
Revises: f741216d7767
Create Date: 2023-06-05 23:14:41.409195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51711970a58c'
down_revision = 'f741216d7767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
