"""trying it5

Revision ID: 6ffc82447010
Revises: 34d5b67e6139
Create Date: 2023-06-05 13:16:24.431204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffc82447010'
down_revision = '34d5b67e6139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
