"""test1

Revision ID: 756200c5045b
Revises: d083e8dfb654
Create Date: 2023-06-05 23:36:18.937843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756200c5045b'
down_revision = 'd083e8dfb654'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
