"""test1

Revision ID: 87e7f624b073
Revises: f25d7101ead6
Create Date: 2023-06-05 23:45:33.234296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e7f624b073'
down_revision = 'f25d7101ead6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
