"""trying it3

Revision ID: 9491838ef7f2
Revises: c7fe0d9ed081
Create Date: 2023-06-05 13:11:03.175771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9491838ef7f2'
down_revision = 'c7fe0d9ed081'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
