"""test

Revision ID: 954736287e78
Revises: d5f6f8a081a1
Create Date: 2023-06-05 22:27:01.611333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954736287e78'
down_revision = 'd5f6f8a081a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
