"""test

Revision ID: 9a00389cd9e5
Revises: 0a05066dcb91
Create Date: 2023-06-07 08:25:57.103720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a00389cd9e5'
down_revision = '0a05066dcb91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
