"""testing

Revision ID: b61b427cd0a6
Revises: a87c333ebb92
Create Date: 2023-06-05 15:16:44.729771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61b427cd0a6'
down_revision = 'a87c333ebb92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
