"""test1

Revision ID: ba2ba39306e9
Revises: 4b2628c7ff19
Create Date: 2023-06-05 23:22:21.822693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2ba39306e9'
down_revision = '4b2628c7ff19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
