"""test1

Revision ID: c3294c1f9256
Revises: e6a7d176846b
Create Date: 2023-06-05 23:21:38.329484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3294c1f9256'
down_revision = 'e6a7d176846b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
