"""trying it2

Revision ID: c7fe0d9ed081
Revises: 690ff08bd0b3
Create Date: 2023-06-05 13:07:24.854027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fe0d9ed081'
down_revision = '690ff08bd0b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
