"""testing

Revision ID: cec58994b04b
Revises: 9d42e6bce07c
Create Date: 2023-06-05 15:11:38.137805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec58994b04b'
down_revision = '9d42e6bce07c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
