"""test1

Revision ID: d083e8dfb654
Revises: dd626489e5ff
Create Date: 2023-06-05 23:35:10.962433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd083e8dfb654'
down_revision = 'dd626489e5ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
