"""test

Revision ID: d4c79c6731d6
Revises: 44ef3d6523f1
Create Date: 2023-06-07 08:22:54.195088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c79c6731d6'
down_revision = '44ef3d6523f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
