"""test

Revision ID: d5f6f8a081a1
Revises: 7d5722a81e48
Create Date: 2023-06-05 22:26:37.227642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f6f8a081a1'
down_revision = '7d5722a81e48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
