"""test1

Revision ID: dd626489e5ff
Revises: ba2ba39306e9
Create Date: 2023-06-05 23:22:39.314071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd626489e5ff'
down_revision = 'ba2ba39306e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
