"""test1

Revision ID: efaf8cdbcc5b
Revises: 27651d1744ab
Create Date: 2023-06-05 22:59:06.881411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaf8cdbcc5b'
down_revision = '27651d1744ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
